package com.hopper.tests.validations.constants;

public enum ResponseValidationField
{
    MERCHANT_OF_RECORD,
    PRICE_CHECK_LINK,
    FENCED_DEAL,
    PROPERTY_LINK_COUNT,
    ROOM_COUNT,
    ROOM_RATES_COUNT,
    PAYMENT_OPTIONS_LINK,
    DEPOSIT_POLICIES_LINK,
    CANCEL_PENALTIES,
    AVAILABLE_ROOMS,
    AMENITIES,
    STATUS,
    BOOKING_LINK,
    SHOPPING_LINK,
    CARD_TYPE,
    OCCUPANCY,
    STAY_PRICE_TYPE,
    NIGHTLY_PRICE_TYPE,
    NIGHTLY_PRICE_COUNT,
    CURRENCY_CODE,
    TOTAL_PRICE,
    BILLABLE_CURRENCY,
    RETRIEVE_BOOKING_LINK,
    RESUME_BOOKING_LINK,
    LINKS,
    ITINERARY_ID,
    RETRIEVE_METHOD,
    RETRIEVE_HREF,
    CANCEL_HREF
    ;
}
